### ISSUE TITLE
this seems like a bad idea securtity-wise 😛

### ISSUE THREAD

**Issue by JohnsonLi** [jiayang/quirrel#6]
https://github.com/jiayang/quirrel/blob/06150eee83ddc2694ba91743bd4669f8997a8a00/cogs/admin.py#L19

https://github.com/jiayang/quirrel/blob/06150eee83ddc2694ba91743bd4669f8997a8a00/cogs/admin.py#L38

**Comment by jiayang** [comment]
Resolved.
